name: Proyecto final DevSecOps

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  sast:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Crear proyecto en SonarQube Cloud
      id: sonarqube_project_creation
      run: |

          set +e
          echo ${{ github.event.repository.name }}
          curl -u "${SONAR_TOKEN}:" "https://sonarcloud.io/api/projects/search?projects=${{ github.event.repository.name }}"

          # El proyecto al parecer no me sale en sonarqube porque lo creé sin visibilidad pública. Entonces hay que eliminarlo solo una vez.
          curl -f -u "${SONAR_TOKEN}:" -X POST \
            "https://sonarcloud.io/api/projects/delete" \
            -d "project=${{ github.event.repository.name }}"

          curl -u "${SONAR_TOKEN}:" "https://sonarcloud.io/api/projects/search?projects=${{ github.event.repository.name }}"
          exit 1
          # Considerar usar siempre comillas dobles. Si no funciona probar cambiando el nombre del proyecto (name y project deben ser iguales siempre)
          curl -f -X POST -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/projects/create" -d "name=${{ github.event.repository.name }}" -d "project=${{ github.event.repository.name }}" -d "organization=jcaresdiplomado" -d "visibility=public"

          if [ $? -ne 0 ]; then
            echo "El proyecto laboratorio-final ya existe, nos saltamos la creación."
          else
            echo "Proyecto laboratorio-final creado exitosamente en SonarQube Cloud."
          #
          fi
          # Ahora elegimos la rama develop como principal si es que no es
          # Ejemplo de salida del curl consultando las ramas:{"branches":[{"name":"master","isMain":true,"type":"LONG","branchId":"b2a7126f-0fdf-4697-8aea-b7e18b793287","branchUuidV1":"AZexjqe1mn08eUWmbf6z"}]}
          MAIN_BRANCH=$(curl -X POST -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/project_branches/list" -d "project=${{ github.event.repository.name }}" | jq -r '.branches[] | select(.isMain == true) | .name')
          if [ "$MAIN_BRANCH" !=  ${GITHUB_REF##*/} ]; then
            echo "Error: La rama principal no es ${GITHUB_REF##*/}, es '$MAIN_BRANCH'."
            echo "Cambiando la rama principal a ${GITHUB_REF##*/}"

            curl -X POST -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/project_branches/rename" -d "project=${{ github.event.repository.name }}" -d "name=${GITHUB_REF##*/}"
            # exit 1
          else
            echo "La rama principal ya es ${GITHUB_REF##*/}."
          fi
          set -e
