name: Proyecto final DevSecOps

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  SONAR_ORGANIZATION: jcaresdiplomado
  RUN_SAST: false

permissions:
  contents: read

jobs:
  SAST:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Crear proyecto en SonarQube Cloud y configurando rama principal
      id: sonarqube_project_creation
      run: |
          set +e
          # Considerar usar siempre comillas dobles. Si no funciona probar cambiando el nombre del proyecto (name y project deben ser iguales siempre)
          # También considerar que sonarqube tiene una db de nombres de proyectos global, por lo tanto elegir nombres de proyectos lo más personalizados posible
          curl -f -X POST -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/projects/create" \
          -d "name=${{ github.event.repository.name }}" \
          -d "project=${{ github.event.repository.name }}" \
          -d "organization=$SONAR_ORGANIZATION" \
          -d "visibility=public"

          if [ $? -ne 0 ]; then
            echo "El proyecto ${{ github.event.repository.name }} ya existe, nos saltamos la creación."
          else
            echo "Proyecto ${{ github.event.repository.name }} creado exitosamente en SonarQube Cloud."
          fi

          # Ahora elegimos la rama develop como principal si es que no es
          # Ejemplo de salida del curl consultando las ramas:{"branches":[{"name":"master","isMain":true,"type":"LONG","branchId":"b2a7126f-0fdf-4697-8aea-b7e18b793287","branchUuidV1":"AZexjqe1mn08eUWmbf6z"}]}
          MAIN_BRANCH=$(curl -X POST -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/project_branches/list" -d "project=${{ github.event.repository.name }}" | jq -r '.branches[] | select(.isMain == true) | .name')
          if [ "$MAIN_BRANCH" !=  ${GITHUB_REF##*/} ]; then
            echo "Error: La rama principal no es ${GITHUB_REF##*/}, es '$MAIN_BRANCH'."
            echo "Cambiando la rama principal a ${GITHUB_REF##*/}"

            curl -X POST -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/project_branches/rename" \
            -d "project=${{ github.event.repository.name }}" \
            -d "name=${GITHUB_REF##*/}"
            # exit 1
          else
            echo "La rama principal ya es ${GITHUB_REF##*/}."
          fi
          set -e

    - name: Ejecutar análisis SAST con SonarQube con action de sonarSoure
      if: ${{ env.RUN_SAST == 'true' }}
      uses: SonarSource/sonarqube-scan-action@v4
      env: 
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=${{ github.event.repository.name }}
          -Dsonar.organization=$SONAR_ORGANIZATION
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.branch.name=${GITHUB_REF##*/}

    - name: Contando vulnerabilidades críticas, altas y medias
      run: |
        SONAR_VULNERABILITIES=$(curl -f -X POST -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/issues/search" \
        -d "componentKeys=${{ github.event.repository.name }}" \
        -d "types=VULNERABILITY" \
        -d "impactSeverities=BLOCKER,HIGH,MEDIUM" | jq '.total')

        if [ "$SONAR_VULNERABILITIES" -ne 0 ]; then
          echo "Número de vulnerabilidades encontradas: $SONAR_VULNERABILITIES "
          exit 1
        fi

    # - name: Ejecutar análisis SAST con SonarQube
    #   id: sonarqube_analysis
    #   run: |
    #       echo "Iniciando análisis SAST con SonarQube..."
    #       sonar-scanner \
    #       -Dsonar.projectKey=${{ github.event.repository.name }} \
    #       -Dsonar.organization=$SONAR_ORGANIZATION \
    #       -Dsonar.host.url=https://sonarcloud.io \
    #       -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
    #       -Dsonar.branch.name=${GITHUB_REF##*/}
    #

  SCA:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Instalar dependencias del proyecto
      run: |
        echo "Instalando dependencias del proyecto..."
        if [ -f "package.json" ]; then
          npm install
        else
          echo "No se encontraron dependencias a instalar."
        fi

    - name: Ejecutar análisis SCA con Dependecy Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: '${{ github.event.repository.name }}'
        path: '.'
        format: 'HTML'
        out: 'reports' # this is the default, no need to specify unless you wish to override it
        args: >
          --failOnCVSS 7
          --enableRetired

    - name: Subiendo el reporte de Dependecy Check como artefacto
      uses: actions/upload-artifact@master
      with:
          name: Reporte Dependency Check
          path: ${{github.workspace}}/reports

