name: Proyecto final DevSecOps

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  SONAR_ORGANIZATION: jcaresdiplomado
  RUN_SAST: false
  RUN_SCA: false
  RUN_CONTAINER_SCAN: false
  RUN_DAST: true

permissions:
  contents: read

jobs:
  SAST:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Crear proyecto en SonarQube Cloud y configurando rama principal
      id: sonarqube_project_creation
      run: |
          set +e
          # Considerar usar siempre comillas dobles. Si no funciona probar cambiando el nombre del proyecto (name y project deben ser iguales siempre)
          # También considerar que sonarqube tiene una db de nombres de proyectos global, por lo tanto elegir nombres de proyectos lo más personalizados posible
          curl -f -X POST -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/projects/create" \
          -d "name=${{ github.event.repository.name }}" \
          -d "project=${{ github.event.repository.name }}" \
          -d "organization=$SONAR_ORGANIZATION" \
          -d "visibility=public"

          if [ $? -ne 0 ]; then
            echo "El proyecto ${{ github.event.repository.name }} ya existe, nos saltamos la creación."
          else
            echo "Proyecto ${{ github.event.repository.name }} creado exitosamente en SonarQube Cloud."
          fi

          # Ahora elegimos la rama develop como principal si es que no es
          # Ejemplo de salida del curl consultando las ramas:{"branches":[{"name":"master","isMain":true,"type":"LONG","branchId":"b2a7126f-0fdf-4697-8aea-b7e18b793287","branchUuidV1":"AZexjqe1mn08eUWmbf6z"}]}
          MAIN_BRANCH=$(curl -X POST -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/project_branches/list" -d "project=${{ github.event.repository.name }}" | jq -r '.branches[] | select(.isMain == true) | .name')
          if [ "$MAIN_BRANCH" !=  ${GITHUB_REF##*/} ]; then
            echo "Error: La rama principal no es ${GITHUB_REF##*/}, es '$MAIN_BRANCH'."
            echo "Cambiando la rama principal a ${GITHUB_REF##*/}"

            curl -X POST -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/project_branches/rename" \
            -d "project=${{ github.event.repository.name }}" \
            -d "name=${GITHUB_REF##*/}"
            # exit 1
          else
            echo "La rama principal ya es ${GITHUB_REF##*/}."
          fi
          set -e

    - name: Ejecutar análisis SAST con SonarQube con action de sonarSoure
      if: ${{ env.RUN_SAST == 'true' }}
      uses: SonarSource/sonarqube-scan-action@v4
      env: 
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=${{ github.event.repository.name }}
          -Dsonar.organization=$SONAR_ORGANIZATION
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.branch.name=${GITHUB_REF##*/}

    - name: Contando vulnerabilidades críticas, altas y medias
      run: |
        SONAR_VULNERABILITIES=$(curl -f -X POST -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/issues/search" \
        -d "componentKeys=${{ github.event.repository.name }}" \
        -d "types=VULNERABILITY" \
        -d "impactSeverities=BLOCKER,HIGH,MEDIUM" | jq '.total')

        if [ "$SONAR_VULNERABILITIES" -ne 0 ]; then
          echo "Número de vulnerabilidades encontradas: $SONAR_VULNERABILITIES "
          exit 1
        fi

    # - name: Ejecutar análisis SAST con SonarQube
    #   id: sonarqube_analysis
    #   run: |
    #       echo "Iniciando análisis SAST con SonarQube..."
    #       sonar-scanner \
    #       -Dsonar.projectKey=${{ github.event.repository.name }} \
    #       -Dsonar.organization=$SONAR_ORGANIZATION \
    #       -Dsonar.host.url=https://sonarcloud.io \
    #       -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
    #       -Dsonar.branch.name=${GITHUB_REF##*/}
    #

  SCA:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Instalar dependencias del proyecto
      if: ${{ env.RUN_SCA == 'true' }}
      run: |
        echo "Instalando dependencias del proyecto..."
        if [ -f "package.json" ]; then
          npm install
        else
          echo "No se encontraron dependencias a instalar."
        fi

    - name: Ejecutar análisis SCA con Dependency Check
      if: ${{ env.RUN_SCA == 'true' }}
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: '${{ github.event.repository.name }}'
        path: '.'
        format: 'JSON'
        out: 'reports'
        # args: >
        #   --failOnCVSS 7
        #   --enableRetired

    - name: Subiendo el reporte de Dependecy Check como artefacto
      if: ${{ env.RUN_SCA == 'true' || always() }}
      uses: actions/upload-artifact@master
      with:
          name: Reporte Dependency Check
          path: ./reports

    - name: Checkeando las vulnerabilidades encontradas
      if: ${{ env.RUN_SCA == 'true' || always() }}
      run: |
        echo "Revisando vulnerabilidades encontradas por Dependency Check..."
        CRITICAL=$(jq '[.dependencies[] | select(.vulnerabilities | type == "array") | select(.vulnerabilities[]?.severity == "CRITICAL")] | length' reports/dependency-check-report.json)
        HIGH=$(jq '[.dependencies[] | select(.vulnerabilities | type == "array") | select(.vulnerabilities[]?.severity == "HIGH")] | length' reports/dependency-check-report.json)
        MEDIUM=$(jq '[.dependencies[] | select(.vulnerabilities | type == "array") | select(.vulnerabilities[]?.severity == "MEDIUM")] | length' reports/dependency-check-report.json)
        echo "Vulnerabilidades críticas: $CRITICAL"
        echo "Vulnerabilidades altas: $HIGH"
        echo "Vulnerabilidades medias: $MEDIUM"

        TOTAL=$((CRITICAL + HIGH + MEDIUM))
        echo "Total de vulnerabilidades encontradas: $TOTAL"

        if [ "$TOTAL" -ne 0 ]; then
          echo "Se encontraron vulnerabilidades críticas, altas o medias."
          exit 1
        else
          echo "No se encontraron vulnerabilidades críticas, altas o medias."
        fi

  DockerBuild:
    runs-on: ubuntu-latest
    if: always()
    needs: [SAST, SCA]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Construir imagen Docker
      run: |
        echo "Construyendo imagen Docker..."
        docker build -t ${{ github.event.repository.name }}:latest .
        ls -la
        echo "Empaquetando la imagen en un targz..."
        docker save ${{ github.event.repository.name }}:latest | gzip > ${{ github.event.repository.name }}.tar.gz
        ls -la

    - name: Subiendo la imagen docker generada como artefacto
      uses: actions/upload-artifact@master
      with:
          name: ${{ github.event.repository.name }}.tar.gz
          path: .

  ContainerScan:
    runs-on: ubuntu-latest
    # if: always()
    needs: DockerBuild

    steps:
    - name: Descargando la imagen docker generada como artefacto en el job DockerBuild
      if: ${{ env.RUN_CONTAINER_SCAN == 'true' }}
      uses: actions/download-artifact@v4
      with:
        name: ${{ github.event.repository.name }}.tar.gz
        path: .

    - name: Descomprimiendo y cargando la imagen docker descargada
      if: ${{ env.RUN_CONTAINER_SCAN == 'true' }}
      run: |
        gunzip -c ./${{ github.event.repository.name }}.tar.gz | docker load

    - name: Ejecutar análisis de seguridad de contenedor con Trivy
      if: ${{ env.RUN_CONTAINER_SCAN == 'true' }}
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ github.event.repository.name }}:latest
        format: 'json'
        output: '${{ github.event.repository.name }}-trivy-report.json'

    - name: Subiendo el reporte de Trivy como artefacto
      if: ${{ env.RUN_CONTAINER_SCAN == 'true' || always() }}
      uses: actions/upload-artifact@master
      with:
          name: ${{ github.event.repository.name }}-trivy-report
          path: ./${{ github.event.repository.name }}-trivy-report.json

    - name: Conteo de vulderabilidades encontradas por trivy
      if: ${{ env.RUN_CONTAINER_SCAN == 'true' || always() }}
      run: |
        CRITICAL=$(jq '.Results[].Vulnerabilities[] | select(.Severity == "CRITICAL") | length' ${{ github.event.repository.name }}-trivy-report.json | wc -l)
        HIGH=$(jq '.Results[].Vulnerabilities[] | select(.Severity == "HIGH") | length' ${{ github.event.repository.name }}-trivy-report.json | wc -l)
        MEDIUM=$(jq '.Results[].Vulnerabilities[] | select(.Severity == "MEDIUM") | length' ${{ github.event.repository.name }}-trivy-report.json | wc -l)
        echo "Número vulnerabilidades críticas: $CRITICAL"
        echo "Número vulnerabilidades altas: $HIGH"
        echo "Número vulnerabilidades medias: $MEDIUM"

        TOTAL=$((CRITICAL + HIGH + MEDIUM))
        echo "Total de vulnerabilidades encontradas: $TOTAL"

        if [ "$TOTAL" -ne 0 ]; then
          echo "Se encontraron vulnerabilidades críticas, altas o medias."
          exit 1
        else
          echo "No se encontraron vulnerabilidades críticas, altas o medias."
        fi

  DAST:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    needs: ContainerScan
    if: always()

    steps:
    - name: Descargando la imagen docker generada como artefacto en el job DockerBuild
      if: ${{ env.RUN_DAST == 'true' }}
      uses: actions/download-artifact@v4
      with:
        name: ${{ github.event.repository.name }}.tar.gz
        path: .

    - name: Descomprimiendo y cargando la imagen docker descargada
      if: ${{ env.RUN_DAST == 'true' }}
      run: |
        gunzip -c ./${{ github.event.repository.name }}.tar.gz | docker load

    - name: Corriendo contenedor de docker para DAST
      if: ${{ env.RUN_DAST == 'true' }}
      run: |
        docker run -d --name ${{ github.event.repository.name }} -p 80:3000 ${{ github.event.repository.name }}:latest
        sleep 30 # Esperar a que el contenedor esté listo

    - name: Ejecutar análisis DAST con OWASP ZAP
      if: ${{ env.RUN_DAST == 'true' }}
      uses: zaproxy/action-full-scan@v0.12.0
      with:
        target: 'http://localhost:80'
        fail-action: false
        report-format: 'json'
        report-file: '${{ github.event.repository.name }}-zap-report.json'
        github-token: ''
        allow_issue_writing: false
        rules_file_name: '.zap/rules.tsv'
        cmd_options: '-a'

    - name: Subiendo el reporte de Trivy como artefacto
      if: ${{ env.RUN_DAST == 'true' }}
      uses: actions/upload-artifact@master
      with:
          name: ${{ github.event.repository.name }}-zap-report
          path: ./${{ github.event.repository.name }}-zap-report.json

    - name: Conteo de vulnerabilidades encontradas por OWASP ZAP
      if: ${{ env.RUN_DAST == 'true' }}
      run: |
        HIGH=$(jq '[.site[].alerts[] | select(.risk == "High")] | length' zap-report.json)
        MEDIUM=$(jq '[.site[].alerts[] | select(.risk == "Medium")] | length' zap-report.json)
        LOW=$(jq '[.site[].alerts[] | select(.risk == "Low")] | length' zap-report.json)
        echo "Número de vulnerabilidades altas: $HIGH"
        echo "Número de vulnerabilidades medias: $MEDIUM"
        echo "Número de vulnerabilidades bajas: $LOW"

        TOTAL=$((HIGH + MEDIUM + LOW))
        echo "Total de vulnerabilidades encontradas: $TOTAL"

        if [ "$TOTAL" -ne 0 ]; then
          echo "Se encontraron vulnerabilidades altas, medias o bajas."
          exit 1
        else
          echo "No se encontraron vulnerabilidades altas, medias o bajas."
        fi

